services:
  # postgres:
  #   container_name: postgres-container
  #   image: postgres:16.4
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/init:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_EXTENSIONS: uuid-ossp
  mysql:
    container_name: mysql-container
    image: mysql:8.4
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: h74geif54j
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
