definitions:
  response.ListTaskResponse:
    properties:
      tasks:
        items:
          $ref: '#/definitions/response.TaskResponse'
        type: array
    type: object
  response.TaskResponse:
    properties:
      create_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      status_id:
        type: integer
      update_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: get tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ListTaskResponse'
      summary: Get tasks
      tags:
      - tasks
swagger: "2.0"
