name: ci

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: install dependencies
        run: go mod download

      - name: install golangci-lint
        run: |
          DOWNLOAD_OS=linux
          DOWNLOAD_ARCH=amd64
          DOWNLOAD_VERSION=1.59.0
          curl -L \
            https://github.com/golangci/golangci-lint/releases/download/v${DOWNLOAD_VERSION}/golangci-lint-${DOWNLOAD_VERSION}-${DOWNLOAD_OS}-${DOWNLOAD_ARCH}.tar.gz \
            -o /tmp/golangci-lint-${DOWNLOAD_VERSION}-${DOWNLOAD_OS}-${DOWNLOAD_ARCH}.tar.gz
          tar -C /tmp -xzf /tmp/golangci-lint-${DOWNLOAD_VERSION}-${DOWNLOAD_OS}-${DOWNLOAD_ARCH}.tar.gz
          mv /tmp/golangci-lint-${DOWNLOAD_VERSION}-${DOWNLOAD_OS}-${DOWNLOAD_ARCH}/golangci-lint /usr/local/bin/

      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: run CI
        run: make test golangci govulncheck
