name: scenario_test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: install dependencies
        run: go mod download

      - name: install swag
        run: |
          DOWNLOAD_OS=Linux
          DOWNLOAD_ARCH=amd64
          DOWNLOAD_VERSION=1.16.3
          curl -L \
            https://github.com/swaggo/swag/releases/download/v${DOWNLOAD_VERSION}/swag_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz \
            -o /tmp/swag_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz
          tar -C /tmp -xzf /tmp/swag_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz
          mv /tmp/swag /usr/local/bin/

      - name: install goreleaser
        run: |
          DOWNLOAD_OS=Linux
          DOWNLOAD_ARCH=x86_64
          DOWNLOAD_VERSION=2.1.0
          curl -L \
            https://github.com/goreleaser/goreleaser/releases/download/v${DOWNLOAD_VERSION}/goreleaser_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz \
            -o /tmp/goreleaser_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz
          tar -C /tmp -xzf /tmp/goreleaser_${DOWNLOAD_OS}_${DOWNLOAD_ARCH}.tar.gz
          mv /tmp/goreleaser /usr/local/bin/

      - name: run scenario test
        run: make up run scenariotest
